name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest' # or specify a specific version

      - name: Install dependencies
        run: bun install

      - name: Publish to npm
        run: bun publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
