# Run unit tests with Bun on every push

name: CI Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # You can specify a version like '1.0.0' if needed

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test
